version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: dockerhub-username
    DOCKER_REGISTRY_PASSWORD: dockerhub-password
    DOCKER_REGISTRY_URL: dockerhub-url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "simple-python-flask-app:latest" .
      - docker tag simple-python-flask-app:latest tellapurisankar/codebuild-repo:latest
      - docker push tellapurisankar/codebuild-repo:latest
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
